### ISSUE TITLE
Compatible with K3d 1.x only

### ISSUE THREAD

**Issue by DblK** [windmilleng/k3d-local-registry#5]
Since I am a mac user, when I update `homebrew` it installed k3d v3.
They did not left the k3d 1.7 binary.

So just for information, waiting for k3d 3.0 compatible script, I have created a [tap to install it](https://github.com/DblK/homebrew-tap).

**Comment by nicks** [comment]
thanks for the report!  

ya, I think k3d had some issues with this release and they cut the registry stuff to get the release out
https://github.com/rancher/k3d/releases/tag/v3.0.0

there's an effort underway to use a registry discovery protocol in k3d v3.1.0 so that this script becomes unnecessary, see:
https://github.com/rancher/k3d/issues/234

**Comment by Tchoupinax** [comment]
Hello,

I relaunch this issue with the release yesterday of the [version 4](https://github.com/rancher/k3d/releases/tag/v4.0.0) of k3d.

The interesting feature is the registry support :

<img width="744" alt="image" src="https://user-images.githubusercontent.com/9136206/105336362-71c99800-5bd9-11eb-81ea-9825be29337d.png">

I think we could rewrite this script with the new release of k3d now it has the registry support. I'm very interested by this update because I use this script to launch all my cluster.

What is the roadmap about this subject ? Maybe I could work on it and offer you a pull request with the new version, but I want to know before if you thought about another direction (like the registry discovery protocol like you mentionned in your previous post).

Keep me informed.
Thank a lot for your work ! <3

**Comment by nicks** [comment]
Hi @Tchoupinax !

We've been working with the k3d team on this! In theory, the new k3d flags should make this script entirely obsolete, since now k3d handles internally everything that this script handles.

I've been testing it out and filing bugs. Plan is to deprecate this repo and point to the k3d instructions once we've verified it. Have you had a chance to try it?

**Comment by Tchoupinax** [comment]
Hello @nicks !

Great new ! 
However, I do not have time yet to explore the new version and to migrate with the new intructions. I saw that the new version provides a "proxy" to free the port 6443 (and maybe have several cluster at the same time I think ? Yeahhh!!).

Yeah, we could deprecate this repo, I only think that if instructions are not clear with k3d docs, It would be very nice to archive this repo and add a section on the readme "Migrate to v4.x" with the equivalent instructions (for current and future users). :)

**Comment by nicks** [comment]
I updated the README with a link to K3d v4.0's instructions!

**Comment by Tchoupinax** [comment]
Thanks !
